# Vector

* 데이터를 효과적으로 저장하고 관리하기 위해서는 기본적인 데이터 타입만으로 부족하고 데이터를 저장하는 구조로서 Object가 설정되어야 함 
    > R에서 함수를 적용하여 분석하고자 할 때 Object별로 사용가능한 함수가 다르다

* Vector 시작
    > a <- 1

In [18]:
a <- 1

In [21]:
b <- 1

In [22]:
vX <- c(1,2)

In [23]:
vX

[1] 1 2

In [24]:
vX.1 <- c(1,2,3,4,5,6,7,8,9,10)

In [25]:
vX.2 <- c(1:10)

In [26]:
vX.2

[1]  1  2  3  4  5  6  7  8  9 10

In [27]:
vX.2 <- c(1:10, 11,12)

In [28]:
vX.2

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [29]:
vX.3 <- c("a", "b")

In [30]:
vX.3

[1] "a" "b"

In [31]:
mode(vX.2)

[1] "numeric"

In [32]:
mode(vX.3)

[1] "character"

In [33]:
vX.4 <- c(vX.1, vX.2)

In [34]:
vX.4

[1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10 11 12

In [35]:
mode(vX.4)

[1] "numeric"

In [36]:
vX.5 <- c("a", 1)

In [37]:
mode(vX.5)

[1] "character"

In [38]:
vX.5

[1] "a" "1"

In [49]:
vX.6<- c(1,2,3,4,5,"6", 7,8,9,10)

In [50]:
vX.6

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [43]:
mode(vX.6)

[1] "character"

In [41]:
sum(vX.6)

ERROR: Error in sum(vX.6): 인자의 'type' (character)이 올바르지 않습니다


In [47]:
vX.7<- c(1,2,3,4,5,6, 7,8,9,10)

In [48]:
vX.7

[1]  1  2  3  4  5  6  7  8  9 10

In [51]:
1:100

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [55]:
odd <- seq(1,100,2)

In [56]:
odd

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

In [57]:
text <- 'a'

In [58]:
text.1 <- "a"

In [59]:
text.2 <- "a's"

In [61]:
print (text.2)

[1] "a's"


In [63]:
odd.1 <- seq(1,10,2)

In [64]:
odd.1

[1] 1 3 5 7 9

In [65]:
odd.1[3]

[1] 5

In [66]:
odd.1[1]

[1] 1

In [67]:
odd.1[c(1,2)]

[1] 1 3

In [69]:
odd.1 <- odd.1[-c(1,2)]

In [70]:
odd.1

[1] 5 7 9

In [71]:
rm(odd.1)

In [72]:
odd.1

ERROR: Error in eval(expr, envir, enclos): 객체 'odd.1'를 찾을 수 없습니다


In [73]:
odd

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

In [74]:
length(odd)

[1] 50

In [75]:
king <- c("태조", "정종", "태종", "세종", "문종", "단종",
         "세조", "예종", "성종", "연산군")

In [76]:
length(king)

[1] 10

In [77]:
grep("예종", king)

[1] 8

In [78]:
grep("종", king)

[1] 2 3 4 5 6 8 9

In [79]:
king[grep("종", king)]

[1] "정종" "태종" "세종" "문종" "단종" "예종" "성종"

In [80]:
king[c(2,3,4,5,6,8,9)]

[1] "정종" "태종" "세종" "문종" "단종" "예종" "성종"

In [81]:
king.1 <- king[-c(2,3,4,5,6,8,9)]

In [82]:
king.1

[1] "태조"   "세조"   "연산군"

In [84]:
king[c(5:length(king))]

[1] "문종"   "단종"   "세조"   "예종"   "성종"   "연산군"

In [96]:
set.seed(1234)
num.text <- sample(10000,100)

In [97]:
length(num.text)

[1] 100

In [99]:
max(num.text)

[1] 9978

In [100]:
min(num.text)

[1] 95

In [101]:
mean(num.text)

[1] 4507.15

In [102]:
median(num.text)

[1] 4614.5

In [103]:
summary(num.text)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     95    2139    4614    4507    6787    9978 

In [104]:
sd(num.text)

[1] 2865.753

In [105]:
var(num.text)

[1] 8212541

In [106]:
num.text > 1000

[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [49]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
 [73] FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [97]  TRUE FALSE  TRUE  TRUE

In [109]:
num.text[num.text > 1000]

[1] 1138 6223 6092 6232 8606 6400 2324 6656 5138 6929 5444 2824 9223 2920 8361
[16] 2858 2664 1864 2318 3160 3021 1587 2183 8086 5244 9122 8291 4548 2644 3037
[31] 5057 1805 7571 2006 2579 9884 8043 5512 6438 3106 6192 3284 4998 6740 4828
[46] 2428 7618 3082 7136 5019 1522 5012 4912 7470 1737 8434 8597 3153 2375 7020
[61] 3061 5052 5607 1207 8865 7775 5153 3814 3182 6633 9190 4681 1415 5398 1946
[76] 8910 3862 9949 9978 8883 1649 8923 1329 1304 1043 5068 2974 3067 7348

In [112]:
num.text[101] <- NA

In [113]:
num.text

[1] 1138 6223 6092 6232 8606 6400   95 2324 6656 5138 6929 5444 2824 9223 2920
 [16] 8361 2858 2664 1864 2318 3160 3021 1587  400 2183 8086 5244 9122 8291  457
 [31] 4548 2644 3037 5057 1805 7571 2006 2579 9884 8043 5512 6438 3106 6192 3284
 [46] 4998 6740 4828 2428 7618  735 3082 7136 5019 1522 5012 4912 7470 1737 8434
 [61] 8597  417 3153  137 2375 7020 3061 5052  513 5607 1207 8865  146 7775  893
 [76] 5153 3814  696 3182 6633 9190 4681 1415 5398 1946 8910 3862 9949 9978 8883
 [91] 1649 8923 1329 1304 1043 5068 2974  265 3067 7348   NA

In [116]:
var(num.text, na.rm = T)

[1] 8212541

In [117]:
sd(num.text, na.rm = T)

[1] 2865.753

In [124]:
is.na(num.text)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE  TRUE

In [125]:
!is.na(num.text)

[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [49]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [97]  TRUE  TRUE  TRUE  TRUE FALSE

In [122]:
num.text[!is.na(num.text)]

[1] 1138 6223 6092 6232 8606 6400   95 2324 6656 5138 6929 5444 2824 9223 2920
 [16] 8361 2858 2664 1864 2318 3160 3021 1587  400 2183 8086 5244 9122 8291  457
 [31] 4548 2644 3037 5057 1805 7571 2006 2579 9884 8043 5512 6438 3106 6192 3284
 [46] 4998 6740 4828 2428 7618  735 3082 7136 5019 1522 5012 4912 7470 1737 8434
 [61] 8597  417 3153  137 2375 7020 3061 5052  513 5607 1207 8865  146 7775  893
 [76] 5153 3814  696 3182 6633 9190 4681 1415 5398 1946 8910 3862 9949 9978 8883
 [91] 1649 8923 1329 1304 1043 5068 2974  265 3067 7348

In [126]:
num.text[102] <- 2341

In [127]:
num.text

[1] 1138 6223 6092 6232 8606 6400   95 2324 6656 5138 6929 5444 2824 9223 2920
 [16] 8361 2858 2664 1864 2318 3160 3021 1587  400 2183 8086 5244 9122 8291  457
 [31] 4548 2644 3037 5057 1805 7571 2006 2579 9884 8043 5512 6438 3106 6192 3284
 [46] 4998 6740 4828 2428 7618  735 3082 7136 5019 1522 5012 4912 7470 1737 8434
 [61] 8597  417 3153  137 2375 7020 3061 5052  513 5607 1207 8865  146 7775  893
 [76] 5153 3814  696 3182 6633 9190 4681 1415 5398 1946 8910 3862 9949 9978 8883
 [91] 1649 8923 1329 1304 1043 5068 2974  265 3067 7348   NA 2341

In [129]:
num.text <- append(num.text, c(20180527,20180528), after = 10)

In [131]:
num.text

[1]     1138     6223     6092     6232     8606     6400       95     2324
  [9]     6656     5138 20180527 20180528     6929     5444     2824     9223
 [17]     2920     8361     2858     2664     1864     2318     3160     3021
 [25]     1587      400     2183     8086     5244     9122     8291      457
 [33]     4548     2644     3037     5057     1805     7571     2006     2579
 [41]     9884     8043     5512     6438     3106     6192     3284     4998
 [49]     6740     4828     2428     7618      735     3082     7136     5019
 [57]     1522     5012     4912     7470     1737     8434     8597      417
 [65]     3153      137     2375     7020     3061     5052      513     5607
 [73]     1207     8865      146     7775      893     5153     3814      696
 [81]     3182     6633     9190     4681     1415     5398     1946     8910
 [89]     3862     9949     9978     8883     1649     8923     1329     1304
 [97]     1043     5068     2974      265     3067     7348       NA     2341

In [135]:
logi <- c(TRUE, FALSE)

In [136]:
logi

[1]  TRUE FALSE

In [137]:
names(king)

NULL

In [139]:
names(king) <- c("1대", "2대", "3대", "4대", "5대",
                "6대", "7대", "8대", "9대", "10대")

In [141]:
king[grep("조", king)]

1대    7대 
"태조" "세조"

In [144]:
num.vx1 <- c(10, 20, 30, 40, 50)
num.vx2 <- c(1,2, 3,4,5)

In [145]:
num.vx1 + num.vx2

[1] 11 22 33 44 55

In [146]:
num.vx1 - num.vx2

[1]  9 18 27 36 45

In [147]:
num.vx1 / num.vx2

[1] 10 10 10 10 10

In [148]:
num.vx1 * num.vx2

[1]  10  40  90 160 250

In [149]:
num.vx1 == num.vx2

[1] FALSE FALSE FALSE FALSE FALSE

<, >, ==, !=

In [150]:
num.vx1 > num.vx2

[1] TRUE TRUE TRUE TRUE TRUE

In [152]:
 10 < 11

[1] TRUE

In [153]:
if( 10 > 11){
    print ("참")
}

if(달걀 == 존재){
    우유 6개 
}

In [154]:
if( 10 > 11){
    print ("참")
}else{
    print ("거짓")
}

[1] "거짓"


In [158]:
15 %% 5

[1] 0

In [162]:
for(sadf in king){
    print (sadf)
}

[1] "태조"
[1] "정종"
[1] "태종"
[1] "세종"
[1] "문종"
[1] "단종"
[1] "세조"
[1] "예종"
[1] "성종"
[1] "연산군"


In [164]:
print (paste(10, "x", 20, "=", 10*20))

[1] "10 x 20 = 200"


In [165]:
for(i in 1:4){
    for(j in 1:4){
        print (j)
    }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 1
[1] 2
[1] 3
[1] 4
[1] 1
[1] 2
[1] 3
[1] 4
[1] 1
[1] 2
[1] 3
[1] 4


In [171]:
TRUE | FALSE 
# or |
# and &

[1] TRUE

In [176]:
for(i in 2:9){
    for (j in 1:9){
        if(i != 5 & i != 6){
            print (paste(i, "x", j, "=", i*j))
        }
        
    }
}

[1] "2 x 1 = 2"
[1] "2 x 2 = 4"
[1] "2 x 3 = 6"
[1] "2 x 4 = 8"
[1] "2 x 5 = 10"
[1] "2 x 6 = 12"
[1] "2 x 7 = 14"
[1] "2 x 8 = 16"
[1] "2 x 9 = 18"
[1] "3 x 1 = 3"
[1] "3 x 2 = 6"
[1] "3 x 3 = 9"
[1] "3 x 4 = 12"
[1] "3 x 5 = 15"
[1] "3 x 6 = 18"
[1] "3 x 7 = 21"
[1] "3 x 8 = 24"
[1] "3 x 9 = 27"
[1] "4 x 1 = 4"
[1] "4 x 2 = 8"
[1] "4 x 3 = 12"
[1] "4 x 4 = 16"
[1] "4 x 5 = 20"
[1] "4 x 6 = 24"
[1] "4 x 7 = 28"
[1] "4 x 8 = 32"
[1] "4 x 9 = 36"
[1] "7 x 1 = 7"
[1] "7 x 2 = 14"
[1] "7 x 3 = 21"
[1] "7 x 4 = 28"
[1] "7 x 5 = 35"
[1] "7 x 6 = 42"
[1] "7 x 7 = 49"
[1] "7 x 8 = 56"
[1] "7 x 9 = 63"
[1] "8 x 1 = 8"
[1] "8 x 2 = 16"
[1] "8 x 3 = 24"
[1] "8 x 4 = 32"
[1] "8 x 5 = 40"
[1] "8 x 6 = 48"
[1] "8 x 7 = 56"
[1] "8 x 8 = 64"
[1] "8 x 9 = 72"
[1] "9 x 1 = 9"
[1] "9 x 2 = 18"
[1] "9 x 3 = 27"
[1] "9 x 4 = 36"
[1] "9 x 5 = 45"
[1] "9 x 6 = 54"
[1] "9 x 7 = 63"
[1] "9 x 8 = 72"
[1] "9 x 9 = 81"


In [181]:
mX <- matrix(1:6, ncol=2)

In [182]:
mX

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [183]:
mX.1 <- matrix(1:6, nrow=2)

In [184]:
mX.1

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [185]:
mX.byrow <- matrix(1:6, ncol=2, byrow = TRUE)

In [186]:
mX.byrow

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [192]:
mX.1 <- matrix(1:12,  nrow = 4,ncol = 3,)

In [190]:
mX.1

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [193]:
mX.2 <- matrix(1:11,  nrow = 4,ncol = 3,)

Warning message in matrix(1:11, nrow = 4, ncol = 3, ):
"데이터의 길이[11]가 행의 개수[4]의 배수가 되지 않습니다"

In [194]:
mX.2

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8     1

In [199]:
mX.3 <- matrix(1:9,  nrow = 4,ncol = 3, byrow = T)

Warning message in matrix(1:9, nrow = 4, ncol = 3, byrow = T):
"데이터의 길이[9]가 행의 개수[4]의 배수가 되지 않습니다"

In [200]:
mX.3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9   
[4,] 1    2    3

In [202]:
mX.4 <- matrix(1:9,  4, 3, byrow = T)

Warning message in matrix(1:9, 4, 3, byrow = T):
"데이터의 길이[9]가 행의 개수[4]의 배수가 되지 않습니다"

In [203]:
mX.4

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9   
[4,] 1    2    3

In [205]:
a.1 <- c(1,2,3)
a.2 <- c(4,5,6)
a.3 <- c(7,8,9)
a.4 <- c(10, 11, 12)

In [208]:
r.Matrix <- rbind(a.1, a.2, a.3, a.4)

In [209]:
c.Matrix <- cbind(a.1, a.2, a.3, a.4)

In [211]:
r.Matrix

[,1] [,2] [,3]
a.1  1    2    3  
a.2  4    5    6  
a.3  7    8    9  
a.4 10   11   12

In [210]:
c.Matrix

a.1 a.2 a.3 a.4
[1,] 1   4   7   10 
[2,] 2   5   8   11 
[3,] 3   6   9   12

In [213]:
rownames(r.Matrix)
colnames(r.Matrix)

[1] "a.1" "a.2" "a.3" "a.4"

NULL

In [214]:
rownames(c.Matrix)
colnames(c.Matrix)

NULL

[1] "a.1" "a.2" "a.3" "a.4"

In [215]:
set.seed(123)
matrix.X <- matrix(sample(100, 25), 5, 5)

In [217]:
matrix.X

[,1] [,2] [,3] [,4] [,5]
[1,] 29    5   87   77   72  
[2,] 79   50   98   21   55  
[3,] 41   83   60    4   90  
[4,] 86   51   94   27   85  
[5,] 91   42    9   78   81

In [219]:
matrix.X[1,3]

[1] 87

In [220]:
matrix.X[c(1,3),c(2,4)]

[,1] [,2]
[1,]  5   77  
[2,] 83    4

In [223]:
matrix.X[, 2]

[1]  5 50 83 51 42

In [224]:
matrix.X

[,1] [,2] [,3] [,4] [,5]
[1,] 29    5   87   77   72  
[2,] 79   50   98   21   55  
[3,] 41   83   60    4   90  
[4,] 86   51   94   27   85  
[5,] 91   42    9   78   81

In [225]:
matrix.X[2, matrix.X[2,] >50]

[1] 79 98 55

In [226]:
matrix.X[2,] >50

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [227]:
matrix.X[2, c(T,F,T,F,T)]

[1] 79 98 55

In [228]:
matrix.X

[,1] [,2] [,3] [,4] [,5]
[1,] 29    5   87   77   72  
[2,] 79   50   98   21   55  
[3,] 41   83   60    4   90  
[4,] 86   51   94   27   85  
[5,] 91   42    9   78   81

In [231]:
matrix.X < 30

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,]  TRUE  TRUE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE  TRUE FALSE
[3,] FALSE FALSE FALSE  TRUE FALSE
[4,] FALSE FALSE FALSE  TRUE FALSE
[5,] FALSE FALSE  TRUE FALSE FALSE

In [230]:
matrix.X[matrix.X < 30]

[1] 29  5  9 21  4 27

In [234]:
matrix.X[-c(1,3), -c(1,5)]

[,1] [,2] [,3]
[1,] 50   98   21  
[2,] 51   94   27  
[3,] 42    9   78

In [236]:
t(mX.3)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    1   
[2,] 2    5    8    2   
[3,] 3    6    9    3

In [243]:
solve.1 <- matrix(c(1,2,3,3,-1,-3, 2,3,1), 3,3, byrow = T)

In [244]:
solve.1

[,1] [,2] [,3]
[1,] 1     2    3  
[2,] 3    -1   -3  
[3,] 2     3    1

In [245]:
solve.2 <- matrix(c(3,-1,4))

In [246]:
solve.2

[,1]
[1,]  3  
[2,] -1  
[3,]  4

In [249]:
solve(solve.1,solve.2)

[,1]     
[1,] 0.2173913
[2,] 1.1304348
[3,] 0.1739130

# list

In [250]:
list.1 <- list("홍길동", c(1,2,3))

In [251]:
list.1

[[1]]
[1] "홍길동"

[[2]]
[1] 1 2 3

In [253]:
list.2 <- list("홍길동", c(1,2,3), solve.1, solve.2, matrix.X)

In [254]:
list.2

[[1]]
[1] "홍길동"

[[2]]
[1] 1 2 3

[[3]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    3   -1   -3
[3,]    2    3    1

[[4]]
     [,1]
[1,]    3
[2,]   -1
[3,]    4

[[5]]
     [,1] [,2] [,3] [,4] [,5]
[1,]   29    5   87   77   72
[2,]   79   50   98   21   55
[3,]   41   83   60    4   90
[4,]   86   51   94   27   85
[5,]   91   42    9   78   81

In [256]:
list.2[3]

[[1]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    3   -1   -3
[3,]    2    3    1

In [258]:
names(list.2) <- c("1번", "2번", "3번", "4번", "5번")

In [259]:
list.2

$`1번`
[1] "홍길동"

$`2번`
[1] 1 2 3

$`3번`
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    3   -1   -3
[3,]    2    3    1

$`4번`
     [,1]
[1,]    3
[2,]   -1
[3,]    4

$`5번`
     [,1] [,2] [,3] [,4] [,5]
[1,]   29    5   87   77   72
[2,]   79   50   98   21   55
[3,]   41   83   60    4   90
[4,]   86   51   94   27   85
[5,]   91   42    9   78   81

# Factor

In [260]:
Factor.1 <- c("very_bad", "bad", "normal", "good", "very_good")

In [261]:
mode(Factor.1)

[1] "character"

In [262]:
is.factor(Factor.1)

[1] FALSE

In [265]:
Factor.1

[1] "very_bad"  "bad"       "normal"    "good"      "very_good"

In [263]:
Factor.2 <- factor(c("very_bad", "bad", "normal", "good", "very_good"))

In [267]:
print (Factor.2)

[1] very_bad  bad       normal    good      very_good
Levels: bad good normal very_bad very_good


In [266]:
is.factor(Factor.2)

[1] TRUE

In [268]:
Factor.3 <- factor(c("A", "B", "C", "D", "F"))

In [269]:
print (Factor.3)

[1] A B C D F
Levels: A B C D F


In [271]:
Factor.3[6] <- "X"

Warning message in `[<-.factor`(`*tmp*`, 6, value = "X"):
"invalid factor level, NA generated"

In [272]:
Factor.3

[1] A    B    C    D    F    <NA>
Levels: A B C D F

In [290]:
gender <- factor(c("여", "여", "여", "남", "남", "여", "여"))

In [291]:
print (gender)

[1] 여 여 여 남 남 여 여
Levels: 남 여


In [295]:
as.double(gender)

[1] 2 2 2 1 1 2 2

In [292]:
gender.2 <- factor(c("여", "여", "여", "남", "남", "여", "여"), levels = c("여", "남"))

In [293]:
print (gender.2)

[1] 여 여 여 남 남 여 여
Levels: 여 남


In [294]:
as.double(gender.2)

[1] 1 1 1 2 2 1 1

In [289]:
print (Factor.4)

[1] 여 여 여 남 남 여 여
Levels: 남 여


In [279]:
gender[10] <- "X"

Warning message in `[<-.factor`(`*tmp*`, 10, value = "X"):
"invalid factor level, NA generated"

In [281]:
gender[10] <- "남"

In [282]:
gender

[1] 여   여   여   남   남   여   여   <NA> <NA> 남  
Levels: 남 여

In [283]:
levels(gender)

[1] "남" "여"

In [284]:
levels(Factor.3)

[1] "A" "B" "C" "D" "F"

In [285]:
as.double(gender)

[1]  2  2  2  1  1  2  2 NA NA  1

In [300]:
test <- c("A", "B", "C", "D", "F")

In [301]:
test

[1] "A" "B" "C" "D" "F"

In [319]:
set.seed(123)
class.1 <- factor(sample(test, 50, replace = T), levels = c("F", "D", "C",
                                                           "B", "A"))

In [320]:
print (class.1)

 [1] B D C F F A C F C C F C D C A F B A B F F D D F D D C C B A F F D D A C D B
[39] B B A C C B A A B C B F
Levels: F D C B A


In [323]:
mean(as.double(class.1) - 1)

[1] 1.9

In [315]:
is.factor(class.1)

[1] TRUE

In [316]:
print (class.1)

 [1] B D C F F A C F C C F C D C A F B A B F F D D F D D C C B A F F D D A C D B
[39] B B A C C B A A B C B F
Levels: A B C D F


# Data.Frame

### matrix는 모든 컬럼이 동일한 데이터 차입을 저장하는 것에 비해 data.frame은 다양한 데이터 타입을 저장할 수 있음

In [326]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [328]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


In [329]:
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [330]:
vX1 <- c(T, F,T)

In [333]:
vX2 <- rnorm(3)

In [334]:
vX2

[1] -1.1381369  1.2538149  0.4264642

In [336]:
df.1 <- data.frame(logic= vX1, value = vX2)

In [339]:
dim(iris)

[1] 150   5

In [344]:
head(iris, 1)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa

In [345]:
tail(iris,1)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
150 5.9          3           5.1          1.8         virginica

In [352]:
df.2 <- data.frame(x = c(1:5), y=seq(1,10,2), z=c("M", "F", "M", "F", "M"), 
                   stringsAsFactors = F)

In [353]:
str(df.2)

'data.frame':	5 obs. of  3 variables:
 $ x: int  1 2 3 4 5
 $ y: num  1 3 5 7 9
 $ z: chr  "M" "F" "M" "F" ...
